[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'

[tool.bandit]
exclude_dirs = ["test"]
targets = ["app"]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
import_heading_stdlib = "Standard Library"
import_heading_firstparty = "First Party"
import_heading_thirdparty = "Third Party"
import_heading_localfolder = "Local Folder"
# Define your project's packages here
known_first_party = ["user_management"]  # Fixed typo
# You can specify third-party packages if needed
known_third_party = ["requests", "fastapi"]  # Add your third-party packages
# Default section for unknown imports
default_section = "THIRDPARTY"
# Add a blank line between sections
lines_between_sections = 1
# Sort imports within sections
force_sort_within_sections = true
